services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5173:5173"
    user: "1000:1000"  # Use your host user's UID:GID for permissions
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - sciencehub_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sciencehub_db_data: