services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5173:5173"
    user: "1000:1000"  # Use your host user's UID:GID for permissions
